/**
 * Generate src/assets_gen.ts — the engine's editorial partials, admin bundle,
 * and site icons embedded as string constants. JSR modules cannot read
 * package-relative files at runtime, so the package ships these inline.
 * assets/ stays the editable source of truth; assets_gen_test.ts pins the
 * generated copy to it. Run `deno task gen` after editing assets/.
 */
import { dirname, fromFileUrl, join } from "jsr:@std/path@1";
import { encodeBase64 } from "jsr:@std/encoding@1/base64";
import { parse as parseJsonc } from "jsr:@std/jsonc@1";

const REPO = dirname(dirname(fromFileUrl(import.meta.url)));

export async function generate(root: string = REPO): Promise<string> {
  const text = (p: string): Promise<string> => Deno.readTextFile(join(root, p));
  const bin = async (p: string): Promise<string> =>
    encodeBase64(await Deno.readFile(join(root, p)));
  const admin: Record<string, string> = {};
  for (const name of ["admin.css", "admin.js", "anchor.js", "layout.js"]) {
    admin[name] = await text(`assets/admin/${name}`);
  }
  const j = (s: string): string => JSON.stringify(s);
  return `// GENERATED by scripts/gen-assets.ts — do not edit. Run: deno task gen
export const EDITORIAL_HEAD: string = ${j(await text("assets/editorial/head.html"))};
export const EDITORIAL_BODY: string = ${j(await text("assets/editorial/body.html"))};
export const ADMIN_ASSETS: Record<string, string> = {
${Object.entries(admin).map(([k, v]) => `  ${j(k)}: ${j(v)},`).join("\n")}
};
export const FAVICON_SVG: string = ${j(await text("favicon.svg"))};
export const APPLE_TOUCH_ICON_B64: string = ${j(await bin("apple-touch-icon.png"))};
`;
}

export async function generateVersion(root: string = REPO): Promise<string> {
  const cfg = parseJsonc(await Deno.readTextFile(join(root, "deno.jsonc"))) as { version: string };
  return `// GENERATED by scripts/gen-assets.ts — do not edit. Run: deno task gen\n` +
    `export const VERSION: string = ${JSON.stringify(cfg.version)};\n`;
}

if (import.meta.main) {
  await Deno.writeTextFile(join(REPO, "src/assets_gen.ts"), await generate());
  console.log("wrote src/assets_gen.ts");
  await Deno.writeTextFile(join(REPO, "src/version.ts"), await generateVersion());
  console.log("wrote src/version.ts");
}
