/**
 * Reading Room — PWA support: the web app manifest and the service worker.
 *
 * Pure, neutral module (no serve-only imports — admin_test.ts pins the build
 * import closure). Shared by BOTH:
 *   - serve.ts  — generates /manifest.webmanifest and /sw.js per request from
 *                 the live corpus, so adding or removing a doc updates the
 *                 service worker on the next navigation.
 *   - build.ts  — writes the same two files into the static output (and the
 *                 shared subset when publishing), so a published instance is
 *                 installable and offline too.
 *
 * The manifest is derived from the content home's `site.jsonc` identity
 * (title, lede) plus the fixed editorial palette, so no new per-machine
 * configuration is required. The service worker precaches the entire corpus
 * ("all the local docs") at install time, then runs network-first so live
 * edits still show when the server is reachable and the cached copy covers
 * the server being unreachable (airplane, machine off, server down).
 *
 * @module
 */
import type { Site } from "./config.ts";
import type { Topic } from "./render.ts";
import { VERSION } from "./version.ts";

/** Editorial light paper (`--bg`). */
const BACKGROUND_COLOR = "#f3ecdd";
/** Editorial forest deep (`--forest-deep`). */
const THEME_COLOR = "#142822";

/** The stable head chrome served/built alongside the docs — the app shell. */
export function precacheUrls(corpus: Topic[]): string[] {
  return [
    "/",
    "/favicon.svg",
    "/apple-touch-icon.png",
    "/icon-192.png",
    "/icon-512.png",
    "/manifest.webmanifest",
    ...corpus.flatMap((t) => t.docs.map((d) => `/docs/${d.slug}`)),
  ];
}

/** FNV-1a 32-bit hex — a cheap deterministic corpus fingerprint. */
function fnv1a(input: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h.toString(16).padStart(8, "0");
}

/** A revision label that changes whenever the corpus or the engine changes. */
export function pwaRevision(corpus: Topic[]): string {
  const slugs = corpus.flatMap((t) => t.docs.map((d) => d.slug)).sort().join("\n");
  return `${VERSION}-${fnv1a(slugs)}`;
}

/** A ≤12-char install label derived from the site title ("The Reading Room" → "Reading Room"). */
export function shortName(title: string): string {
  const t = title.replace(/^The\s+/i, "").trim();
  return t.length <= 12 ? t : t.slice(0, 12).trimEnd();
}

/**
 * The web app manifest, as JSON text. `name`/`description` ride the content
 * home's `site.jsonc` identity; colors are the fixed editorial palette.
 */
export function renderManifest(site: Site): string {
  return JSON.stringify(
    {
      id: "/",
      name: site.title,
      short_name: shortName(site.title),
      description: site.lede,
      start_url: "/",
      scope: "/",
      display: "standalone",
      background_color: BACKGROUND_COLOR,
      theme_color: THEME_COLOR,
      icons: [
        { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
        { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
        { src: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
        { src: "/favicon.svg", sizes: "any", type: "image/svg+xml" },
      ],
    },
    null,
    2,
  );
}

/**
 * The service worker source, with the current corpus baked into a precache
 * list and a revision label. Bytes change whenever the corpus (or engine
 * version) changes, so browsers install the updated worker and re-precache
 * after any registry edit — no manual refresh dance.
 */
export function renderServiceWorker(corpus: Topic[]): string {
  const revision = pwaRevision(corpus);
  const urls = precacheUrls(corpus);
  return `// Reading Room service worker — generated by the engine (src/pwa.ts).
// Precaches the whole local corpus for offline reading, then runs
// network-first so live edits still show when the server is reachable.
const BUILD = ${JSON.stringify(revision)};
const CACHE = "reading-room-" + BUILD;
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  const isNavigation = request.mode === "navigate";
  const isDoc = url.pathname.startsWith("/docs/");
  const isPrecached = PRECACHE.indexOf(url.pathname) !== -1;

  // Pages and docs: network-first. Fresh content wins when the server is
  // reachable (live edits appear on refresh); the precache (and runtime
  // cache) covers the server being unreachable.
  if (isNavigation || isDoc) {
    event.respondWith(
      fetch(request).then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      }).catch(() =>
        caches.match(request).then((hit) => hit || caches.match("/"))
      )
    );
    return;
  }

  // Stable precached assets (icons, manifest): cache-first, network fallback.
  if (isPrecached) {
    event.respondWith(
      caches.match(request).then((hit) => hit || fetch(request))
    );
  }
});
`;
}
